// packages/demo-react-native/app/radio-group.tsx
import { View, Text, Pressable, StyleSheet, ScrollView } from "react-native";
import { useLogic } from "@component-library/react-native";
import { RadioGroupLogic } from "@component-library/core";
import type { ValidationRule } from "@component-library/core";
import { StateDebug } from "../components/StateDebug";
import { ValidationErrors } from "../components/ValidationErrors";
import { Colors, Spacing, Radius } from "../constants/theme";

type Size = "sm" | "md" | "lg" | "xl";

const options: { value: Size; label: string; description: string }[] = [
  { value: "sm", label: "Small", description: "For compact layouts" },
  { value: "md", label: "Medium", description: "Default size" },
  { value: "lg", label: "Large", description: "For prominent elements" },
  { value: "xl", label: "Extra Large", description: "For hero sections" },
];

const required = (): ValidationRule<Size | null> => ({
  name: "required",
  validate: (v) => (v ? null : "Please select a size"),
});

export default function RadioGroupScreen() {
  const [state, logic] = useLogic(
    () =>
      new RadioGroupLogic<Size>({
        rules: [required()],
        validateOnChange: true,
      })
  );

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.label}>Component size</Text>

      <View style={styles.radioGroup} accessibilityRole="radiogroup">
        {options.map((opt) => {
          const selected = state.value === opt.value;
          return (
            <Pressable
              key={opt.value}
              style={[styles.radioRow, selected && styles.radioRowSelected]}
              onPress={() => logic.setValue(opt.value)}
              accessibilityRole="radio"
              accessibilityState={{ selected }}
            >
              <View style={[styles.radio, selected && styles.radioSelected]}>
                {selected && <View style={styles.radioDot} />}
              </View>
              <View style={styles.radioContent}>
                <Text style={[styles.radioLabel, selected && styles.radioLabelSelected]}>
                  {opt.label}
                </Text>
                <Text style={styles.radioDescription}>{opt.description}</Text>
              </View>
            </Pressable>
          );
        })}
      </View>

      <ValidationErrors validation={state.validation} show={state.touched} />

      <StateDebug
        state={{
          value: state.value ?? "null",
          touched: state.touched,
          dirty: state.dirty,
          valid: state.validation.valid,
        }}
      />

      <View style={styles.actions}>
        <Pressable style={styles.button} onPress={() => logic.reset()}>
          <Text style={styles.buttonText}>Reset</Text>
        </Pressable>
        <Pressable style={styles.button} onPress={() => logic.validate()}>
          <Text style={styles.buttonText}>Validate</Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.surface },
  content: { padding: Spacing.xl, gap: Spacing.md },
  label: { fontSize: 14, fontWeight: "600", color: Colors.text },
  radioGroup: { gap: Spacing.sm },
  radioRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
  },
  radioRowSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryLight,
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  radioSelected: {
    borderColor: Colors.primary,
  },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.primary,
  },
  radioContent: { flex: 1 },
  radioLabel: { fontSize: 15, fontWeight: "500", color: Colors.text },
  radioLabelSelected: { color: Colors.primary },
  radioDescription: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  actions: { flexDirection: "row", gap: Spacing.sm },
  button: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surface,
  },
  buttonText: { fontSize: 14, color: Colors.text },
});

// packages/demo-svelte/src/routes/radio-group/+page.svelte
<script lang="ts">
  import { useLogic } from "@component-library/svelte";
  import { RadioGroupLogic } from "@component-library/core";

  type Color = "red" | "green" | "blue";
  const options: { value: Color; label: string }[] = [
    { value: "red", label: "Red" },
    { value: "green", label: "Green" },
    { value: "blue", label: "Blue" },
  ];

  const required = () => ({
    name: "required",
    validate: (v: Color | null) => (v ? null : "Please select a color"),
  });

  const logic = new RadioGroupLogic<Color>({
    rules: [required()],
  });

  const state = useLogic(logic);
</script>

<h2>RadioGroup</h2>

<div class="demo">
  <fieldset>
    <legend>Favorite color</legend>
    {#each options as opt}
      <label class="radio-label">
        <input
          type="radio"
          name="color"
          value={opt.value}
          checked={state.current.value === opt.value}
          onchange={() => logic.setValue(opt.value)}
          onfocus={() => logic.focus()}
          onblur={() => logic.blur()}
        />
        {opt.label}
      </label>
    {/each}
  </fieldset>

  {#if !state.current.validation.valid && state.current.touched}
    <ul class="errors">
      {#each state.current.validation.errors as err}
        <li>{err}</li>
      {/each}
    </ul>
  {/if}

  <div class="state-debug">
    <strong>State:</strong>
    <code>
      value={state.current.value ?? "null"} | touched={state.current.touched} |
      dirty={state.current.dirty} | valid={state.current.validation.valid}
    </code>
  </div>

  <div class="actions">
    <button onclick={() => logic.reset()}>Reset</button>
    <button onclick={() => logic.validate()}>Validate</button>
  </div>
</div>

<style>
  .demo {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  fieldset {
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    padding: 0.75rem 1rem;
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }
  legend {
    font-weight: 600;
    font-size: 0.875rem;
    padding: 0 0.25rem;
  }
  .radio-label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.875rem;
    cursor: pointer;
  }
  .errors {
    color: var(--color-error);
    font-size: 0.8rem;
    padding-left: 1rem;
  }
  .state-debug {
    font-size: 0.75rem;
    color: var(--color-text-muted);
    background: var(--color-bg);
    padding: 0.5rem;
    border-radius: var(--radius);
  }
  .state-debug code {
    display: block;
    margin-top: 0.25rem;
  }
  .actions {
    display: flex;
    gap: 0.5rem;
  }
  button {
    padding: 0.375rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    background: var(--color-surface);
    cursor: pointer;
    font-size: 0.8rem;
  }
  button:hover {
    background: var(--color-bg);
  }
</style>
