// packages/demo-svelte/src/routes/accordion/+page.svelte
<script lang="ts">
  import { useLogic } from "@component-library/svelte";
  import { AccordionLogic } from "@component-library/core";

  const items = [
    {
      id: "what",
      title: "What is this library?",
      content:
        "A headless, framework-agnostic component library. Business logic lives in pure TypeScript, with thin adapters for Svelte and React Native.",
    },
    {
      id: "how",
      title: "How does it work?",
      content:
        "Each component has a Logic class in core that manages state via an observable Store. Framework packages subscribe to that store using their native reactivity primitives.",
    },
    {
      id: "why",
      title: "Why headless?",
      content:
        "Headless components give you full control over markup and styling while reusing battle-tested logic. You get accessibility and state management without being locked into a design system.",
    },
  ];

  const logic = new AccordionLogic({
    initialExpanded: ["what"],
    multiple: false,
    collapsible: true,
  });

  const state = useLogic(logic);
</script>

<h2>Accordion</h2>

<div class="demo">
  <div class="accordion">
    {#each items as item}
      <div class="accordion-item">
        <button
          class="accordion-trigger"
          class:expanded={state.current.expandedItems.has(item.id)}
          onclick={() => logic.toggle(item.id)}
        >
          <span>{item.title}</span>
          <span class="icon">
            {state.current.expandedItems.has(item.id) ? "−" : "+"}
          </span>
        </button>
        {#if state.current.expandedItems.has(item.id)}
          <div class="accordion-content">
            <p>{item.content}</p>
          </div>
        {/if}
      </div>
    {/each}
  </div>

  <div class="state-debug">
    <strong>State:</strong>
    <code>
      expanded=[{[...state.current.expandedItems].join(", ")}]
    </code>
  </div>

  <div class="actions">
    <button onclick={() => logic.expandAll(items.map((i) => i.id))}>
      Expand All
    </button>
    <button onclick={() => logic.collapseAll()}>Collapse All</button>
  </div>
</div>

<style>
  .demo {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }
  .accordion {
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    overflow: hidden;
  }
  .accordion-item + .accordion-item {
    border-top: 1px solid var(--color-border);
  }
  .accordion-trigger {
    width: 100%;
    padding: 0.75rem 1rem;
    border: none;
    background: var(--color-surface);
    font-size: 0.875rem;
    font-weight: 600;
    text-align: left;
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .accordion-trigger:hover {
    background: var(--color-bg);
  }
  .accordion-trigger.expanded {
    background: var(--color-bg);
  }
  .icon {
    font-size: 1rem;
    color: var(--color-text-muted);
  }
  .accordion-content {
    padding: 0.75rem 1rem;
    font-size: 0.875rem;
    line-height: 1.5;
    border-top: 1px solid var(--color-border);
  }
  .state-debug {
    font-size: 0.75rem;
    color: var(--color-text-muted);
    background: var(--color-bg);
    padding: 0.5rem;
    border-radius: var(--radius);
  }
  .state-debug code {
    display: block;
    margin-top: 0.25rem;
  }
  .actions {
    display: flex;
    gap: 0.5rem;
  }
  button {
    padding: 0.375rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    background: var(--color-surface);
    cursor: pointer;
    font-size: 0.8rem;
  }
  button:hover {
    background: var(--color-bg);
  }
</style>

// packages/demo-react-native/app/accordion.tsx
import { View, Text, Pressable, StyleSheet, ScrollView, LayoutAnimation, UIManager, Platform } from "react-native";
import { useLogic } from "@component-library/react-native";
import { AccordionLogic } from "@component-library/core";
import type { AccordionItem } from "@component-library/core";
import { StateDebug } from "../components/StateDebug";
import { Colors, Spacing, Radius } from "../constants/theme";

// Enable LayoutAnimation on Android
if (Platform.OS === "android" && UIManager.setLayoutAnimationEnabledExperimental) {
  UIManager.setLayoutAnimationEnabledExperimental(true);
}

const items: (AccordionItem & { title: string; content: string })[] = [
  {
    id: "what",
    title: "What is this library?",
    content:
      "A headless, framework-agnostic component library. Business logic lives in pure TypeScript, with thin adapters for Svelte and React Native.",
  },
  {
    id: "how",
    title: "How does it work?",
    content:
      "Each component has a Logic class in core that manages state via an observable Store. Framework packages subscribe to that store using their native reactivity primitives.",
  },
  {
    id: "disabled",
    title: "This item is disabled",
    content: "You should never see this.",
    disabled: true,
  },
  {
    id: "why",
    title: "Why headless?",
    content:
      "Headless components give you full control over markup and styling while reusing battle-tested logic. You get accessibility and state management without being locked into a design system.",
  },
];

export default function AccordionScreen() {
  const [state, logic] = useLogic(
    () =>
      new AccordionLogic({
        items,
        initialExpanded: ["what"],
        multiple: true,
        collapsible: true,
      })
  );

  const handleToggle = (id: string) => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    logic.toggle(id);
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.accordion}>
        {items.map((item, index) => {
          const expanded = state.expandedItems.has(item.id);
          const isDisabled = !!item.disabled;
          const isFirst = index === 0;
          const isLast = index === items.length - 1;

          return (
            <View
              key={item.id}
              style={[
                styles.item,
                !isFirst && styles.itemBorder,
                isDisabled && styles.itemDisabled,
              ]}
            >
              <Pressable
                style={[
                  styles.trigger,
                  expanded && styles.triggerExpanded,
                  isFirst && styles.triggerFirst,
                  isLast && !expanded && styles.triggerLast,
                ]}
                onPress={() => handleToggle(item.id)}
                disabled={isDisabled}
                accessibilityRole="button"
                accessibilityState={{ expanded, disabled: isDisabled }}
              >
                <Text style={styles.triggerText}>{item.title}</Text>
                <Text style={styles.chevron}>{expanded ? "▲" : "▼"}</Text>
              </Pressable>

              {expanded && (
                <View
                  style={[styles.panel, isLast && styles.panelLast]}
                  accessibilityRole="summary"
                >
                  <Text style={styles.panelText}>{item.content}</Text>
                </View>
              )}
            </View>
          );
        })}
      </View>

      <StateDebug
        state={{
          expanded: state.expandedItems,
          focused: state.focusedItemId ?? "none",
        }}
      />

      <View style={styles.actions}>
        <Pressable style={styles.button} onPress={() => {
          LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
          logic.expandAll();
        }}>
          <Text style={styles.buttonText}>Expand All</Text>
        </Pressable>
        <Pressable style={styles.button} onPress={() => {
          LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
          logic.collapseAll();
        }}>
          <Text style={styles.buttonText}>Collapse All</Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.surface },
  content: { padding: Spacing.xl, gap: Spacing.md },
  accordion: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    overflow: "hidden",
  },
  item: {},
  itemBorder: { borderTopWidth: 1, borderTopColor: Colors.border },
  itemDisabled: { opacity: 0.5 },
  trigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md + 2,
    backgroundColor: Colors.surface,
  },
  triggerExpanded: { backgroundColor: Colors.background },
  triggerFirst: {
    borderTopLeftRadius: Radius.md,
    borderTopRightRadius: Radius.md,
  },
  triggerLast: {
    borderBottomLeftRadius: Radius.md,
    borderBottomRightRadius: Radius.md,
  },
  triggerText: { fontSize: 15, fontWeight: "600", color: Colors.text, flex: 1 },
  chevron: { fontSize: 10, color: Colors.textMuted },
  panel: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  panelLast: {
    borderBottomLeftRadius: Radius.md,
    borderBottomRightRadius: Radius.md,
  },
  panelText: { fontSize: 14, lineHeight: 21, color: Colors.text },
  actions: { flexDirection: "row", gap: Spacing.sm },
  button: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surface,
  },
  buttonText: { fontSize: 14, color: Colors.text },
});
