// packages/demo-svelte/src/routes/checkbox/+page.svelte
<script lang="ts">
  import { useLogic } from "@component-library/svelte";
  import { CheckboxLogic } from "@component-library/core";

  const mustAccept = () => ({
    name: "mustAccept",
    validate: (v: boolean) => (v ? null : "You must accept the terms"),
  });

  const logic = new CheckboxLogic({
    rules: [mustAccept()],
  });

  const state = useLogic(logic);
</script>

<h2>Checkbox</h2>

<div class="demo">
  <label class="checkbox-label">
    <input
      type="checkbox"
      checked={state.current.checked}
      onchange={() => logic.toggle()}
      onfocus={() => logic.focus()}
      onblur={() => logic.blur()}
    />
    I accept the terms and conditions
  </label>

  {#if !state.current.validation.valid && state.current.touched}
    <ul class="errors">
      {#each state.current.validation.errors as err}
        <li>{err}</li>
      {/each}
    </ul>
  {/if}

  <div class="state-debug">
    <strong>State:</strong>
    <code>
      checked={state.current.checked} | touched={state.current.touched} |
      dirty={state.current.dirty} | valid={state.current.validation.valid}
    </code>
  </div>

  <div class="actions">
    <button onclick={() => logic.reset()}>Reset</button>
    <button onclick={() => logic.validate()}>Validate</button>
  </div>
</div>

<style>
  .demo {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .checkbox-label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.875rem;
    cursor: pointer;
  }
  .errors {
    color: var(--color-error);
    font-size: 0.8rem;
    padding-left: 1rem;
  }
  .state-debug {
    font-size: 0.75rem;
    color: var(--color-text-muted);
    background: var(--color-bg);
    padding: 0.5rem;
    border-radius: var(--radius);
  }
  .state-debug code {
    display: block;
    margin-top: 0.25rem;
  }
  .actions {
    display: flex;
    gap: 0.5rem;
  }
  button {
    padding: 0.375rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    background: var(--color-surface);
    cursor: pointer;
    font-size: 0.8rem;
  }
  button:hover {
    background: var(--color-bg);
  }
</style>

// packages/demo-react-native/app/checkbox.tsx
import { View, Text, Pressable, StyleSheet, ScrollView } from "react-native";
import { useLogic } from "@component-library/react-native";
import { CheckboxLogic } from "@component-library/core";
import type { ValidationRule } from "@component-library/core";
import { StateDebug } from "../components/StateDebug";
import { ValidationErrors } from "../components/ValidationErrors";
import { Colors, Spacing, Radius } from "../constants/theme";

const mustAccept = (): ValidationRule<boolean> => ({
  name: "mustAccept",
  validate: (v) => (v ? null : "You must accept the terms"),
});

export default function CheckboxScreen() {
  const [state, logic] = useLogic(
    () =>
      new CheckboxLogic({
        rules: [mustAccept()],
        validateOnChange: true,
      })
  );

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Pressable
        style={styles.checkboxRow}
        onPress={() => logic.toggle()}
        accessibilityRole="checkbox"
        accessibilityState={{ checked: state.checked }}
      >
        <View
          style={[styles.checkbox, state.checked && styles.checkboxChecked]}
        >
          {state.checked && <Text style={styles.checkmark}>✓</Text>}
        </View>
        <Text style={styles.checkboxLabel}>I accept the terms and conditions</Text>
      </Pressable>

      <ValidationErrors validation={state.validation} show={state.touched} />

      <StateDebug
        state={{
          checked: state.checked,
          touched: state.touched,
          dirty: state.dirty,
          valid: state.validation.valid,
        }}
      />

      <View style={styles.actions}>
        <Pressable style={styles.button} onPress={() => logic.reset()}>
          <Text style={styles.buttonText}>Reset</Text>
        </Pressable>
        <Pressable style={styles.button} onPress={() => logic.validate()}>
          <Text style={styles.buttonText}>Validate</Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.surface },
  content: { padding: Spacing.xl, gap: Spacing.md },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  checkmark: {
    color: Colors.textInverse,
    fontSize: 14,
    fontWeight: "700",
  },
  checkboxLabel: {
    fontSize: 15,
    color: Colors.text,
    flex: 1,
  },
  actions: { flexDirection: "row", gap: Spacing.sm },
  button: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surface,
  },
  buttonText: { fontSize: 14, color: Colors.text },
});
