// packages/demo-svelte/src/routes/text-field/+page.svelte
<script lang="ts">
  import { useLogic } from "@component-library/svelte";
  import { TextFieldLogic } from "@component-library/core";

  // Inline validation rules matching the core API
  const required = () => ({
    name: "required",
    validate: (v: string) => (v.trim() ? null : "This field is required"),
  });
  const minLength = (min: number) => ({
    name: "minLength",
    validate: (v: string) =>
      v.length >= min ? null : `Must be at least ${min} characters`,
  });

  const logic = new TextFieldLogic({
    rules: [required(), minLength(3)],
    validateOnBlur: true,
    validateOnChange: false,
  });

  const state = useLogic(logic);
</script>

<h2>TextField</h2>

<div class="demo">
  <label for="demo-input">Username</label>
  <input
    id="demo-input"
    type="text"
    placeholder="Enter username"
    value={state.current.value}
    oninput={(e) => logic.setValue(e.currentTarget.value)}
    onfocus={() => logic.focus()}
    onblur={() => logic.blur()}
  />

  {#if !state.current.validation.valid && state.current.touched}
    <ul class="errors">
      {#each state.current.validation.errors as err}
        <li>{err}</li>
      {/each}
    </ul>
  {/if}

  <div class="state-debug">
    <strong>State:</strong>
    <code>
      value="{state.current.value}" | touched={state.current.touched} |
      dirty={state.current.dirty} | focused={state.current.focused} |
      valid={state.current.validation.valid}
    </code>
  </div>

  <div class="actions">
    <button onclick={() => logic.reset()}>Reset</button>
    <button onclick={() => logic.validate()}>Validate</button>
  </div>
</div>

<style>
  .demo {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  label {
    font-weight: 600;
    font-size: 0.875rem;
  }
  input {
    padding: 0.5rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    font-size: 0.875rem;
  }
  input:focus {
    outline: none;
    border-color: var(--color-border-focus);
    box-shadow: 0 0 0 2px rgba(79, 70, 229, 0.15);
  }
  .errors {
    color: var(--color-error);
    font-size: 0.8rem;
    padding-left: 1rem;
  }
  .state-debug {
    font-size: 0.75rem;
    color: var(--color-text-muted);
    background: var(--color-bg);
    padding: 0.5rem;
    border-radius: var(--radius);
  }
  .state-debug code {
    display: block;
    margin-top: 0.25rem;
    word-break: break-all;
  }
  .actions {
    display: flex;
    gap: 0.5rem;
  }
  button {
    padding: 0.375rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    background: var(--color-surface);
    cursor: pointer;
    font-size: 0.8rem;
  }
  button:hover {
    background: var(--color-bg);
  }
</style>

// packages/demo-react-native/app/text-field.tsx
import { View, Text, TextInput, Pressable, StyleSheet, ScrollView } from "react-native";
import { useLogic } from "@component-library/react-native";
import { TextFieldLogic } from "@component-library/core";
import type { ValidationRule } from "@component-library/core";
import { StateDebug } from "../components/StateDebug";
import { ValidationErrors } from "../components/ValidationErrors";
import { Colors, Spacing, Radius } from "../constants/theme";

const required = (): ValidationRule<string> => ({
  name: "required",
  validate: (v) => (v.trim() ? null : "This field is required"),
});

const minLength = (min: number): ValidationRule<string> => ({
  name: "minLength",
  validate: (v) => (v.length >= min ? null : `Minimum ${min} characters`),
});

export default function TextFieldScreen() {
  const [state, logic] = useLogic(
    () =>
      new TextFieldLogic({
        rules: [required(), minLength(3)],
        validateOnBlur: true,
        validateOnChange: false,
      })
  );

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.label}>Username</Text>

      <TextInput
        style={[
          styles.input,
          state.focused && styles.inputFocused,
          !state.validation.valid && state.touched && styles.inputError,
        ]}
        value={state.value}
        placeholder="Enter username"
        placeholderTextColor={Colors.textMuted}
        onChangeText={(v) => logic.setValue(v)}
        onFocus={() => logic.focus()}
        onBlur={() => logic.blur()}
        autoCapitalize="none"
        autoCorrect={false}
      />

      <ValidationErrors validation={state.validation} show={state.touched} />

      <StateDebug
        state={{
          value: state.value || '""',
          touched: state.touched,
          dirty: state.dirty,
          focused: state.focused,
          valid: state.validation.valid,
        }}
      />

      <View style={styles.actions}>
        <Pressable style={styles.button} onPress={() => logic.reset()}>
          <Text style={styles.buttonText}>Reset</Text>
        </Pressable>
        <Pressable style={styles.button} onPress={() => logic.validate()}>
          <Text style={styles.buttonText}>Validate</Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.surface },
  content: { padding: Spacing.xl, gap: Spacing.md },
  label: { fontSize: 14, fontWeight: "600", color: Colors.text },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm + 2,
    fontSize: 15,
    color: Colors.text,
    backgroundColor: Colors.surface,
  },
  inputFocused: {
    borderColor: Colors.borderFocus,
    borderWidth: 2,
  },
  inputError: {
    borderColor: Colors.error,
  },
  actions: { flexDirection: "row", gap: Spacing.sm },
  button: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surface,
  },
  buttonText: { fontSize: 14, color: Colors.text },
});
