// packages/demo-react-native/app/select.tsx
import {
  View,
  Text,
  Pressable,
  Modal,
  FlatList,
  StyleSheet,
  ScrollView,
} from "react-native";
import { useLogic } from "@component-library/react-native";
import { SelectLogic } from "@component-library/core";
import type { SelectOption, ValidationRule } from "@component-library/core";
import { StateDebug } from "../components/StateDebug";
import { ValidationErrors } from "../components/ValidationErrors";
import { Colors, Spacing, Radius } from "../constants/theme";

type Fruit = "apple" | "banana" | "cherry" | "mango" | "strawberry";

const fruits: SelectOption<Fruit>[] = [
  { value: "apple", label: "🍎 Apple" },
  { value: "banana", label: "🍌 Banana" },
  { value: "cherry", label: "🍒 Cherry" },
  { value: "mango", label: "🥭 Mango" },
  { value: "strawberry", label: "🍓 Strawberry" },
];

const required = (): ValidationRule<Fruit | null> => ({
  name: "required",
  validate: (v) => (v ? null : "Please select a fruit"),
});

export default function SelectScreen() {
  const [state, logic] = useLogic(
    () =>
      new SelectLogic<Fruit>({
        options: fruits,
        rules: [required()],
        validateOnBlur: true,
        validateOnChange: false,
      })
  );

  const selectedLabel = fruits.find((o) => o.value === state.value)?.label;

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.label}>Favorite fruit</Text>

      <Pressable
        style={[styles.trigger, state.open && styles.triggerOpen]}
        onPress={() => logic.toggleMenu()}
        accessibilityRole="button"
        accessibilityState={{ expanded: state.open }}
      >
        <Text style={selectedLabel ? styles.triggerText : styles.placeholder}>
          {selectedLabel ?? "Choose a fruit…"}
        </Text>
        <Text style={styles.chevron}>{state.open ? "▲" : "▼"}</Text>
      </Pressable>

      <Modal
        visible={state.open}
        transparent
        animationType="fade"
        onRequestClose={() => logic.closeMenu()}
      >
        <Pressable style={styles.overlay} onPress={() => logic.closeMenu()}>
          <View style={styles.dropdown}>
            <Text style={styles.dropdownTitle}>Select a fruit</Text>
            <FlatList
              data={fruits}
              keyExtractor={(item) => item.value}
              renderItem={({ item, index }) => {
                const isSelected = state.value === item.value;
                const isHighlighted = state.highlightedIndex === index;
                return (
                  <Pressable
                    style={[
                      styles.option,
                      isHighlighted && styles.optionHighlighted,
                      isSelected && styles.optionSelected,
                    ]}
                    onPress={() => logic.setValue(item.value)}
                    accessibilityRole="menuitem"
                    accessibilityState={{ selected: isSelected }}
                  >
                    <Text
                      style={[
                        styles.optionText,
                        isSelected && styles.optionTextSelected,
                      ]}
                    >
                      {item.label}
                    </Text>
                    {isSelected && <Text style={styles.checkIcon}>✓</Text>}
                  </Pressable>
                );
              }}
            />
          </View>
        </Pressable>
      </Modal>

      <ValidationErrors validation={state.validation} show={state.touched} />

      <StateDebug
        state={{
          value: state.value ?? "null",
          open: state.open,
          highlighted: state.highlightedIndex,
          touched: state.touched,
          valid: state.validation.valid,
        }}
      />

      <View style={styles.actions}>
        <Pressable style={styles.button} onPress={() => logic.reset()}>
          <Text style={styles.buttonText}>Reset</Text>
        </Pressable>
        <Pressable style={styles.button} onPress={() => logic.validate()}>
          <Text style={styles.buttonText}>Validate</Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.surface },
  content: { padding: Spacing.xl, gap: Spacing.md },
  label: { fontSize: 14, fontWeight: "600", color: Colors.text },
  trigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm + 2,
  },
  triggerOpen: { borderColor: Colors.borderFocus, borderWidth: 2 },
  triggerText: { fontSize: 15, color: Colors.text },
  placeholder: { fontSize: 15, color: Colors.textMuted },
  chevron: { fontSize: 10, color: Colors.textMuted },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    padding: Spacing.xl,
  },
  dropdown: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    maxHeight: 320,
    overflow: "hidden",
  },
  dropdownTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.text,
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  optionHighlighted: { backgroundColor: Colors.background },
  optionSelected: { backgroundColor: Colors.primaryLight },
  optionText: { fontSize: 15, color: Colors.text },
  optionTextSelected: { color: Colors.primary, fontWeight: "600" },
  checkIcon: { color: Colors.primary, fontSize: 16, fontWeight: "700" },
  actions: { flexDirection: "row", gap: Spacing.sm },
  button: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surface,
  },
  buttonText: { fontSize: 14, color: Colors.text },
});

// packages/demo-svelte/src/routes/select/+page.svelte
<script lang="ts">
  import { useLogic } from "@component-library/svelte";
  import { SelectLogic } from "@component-library/core";

  type Fruit = "apple" | "banana" | "cherry" | "mango";
  const options: { value: Fruit; label: string }[] = [
    { value: "apple", label: "Apple" },
    { value: "banana", label: "Banana" },
    { value: "cherry", label: "Cherry" },
    { value: "mango", label: "Mango" },
  ];

  const required = () => ({
    name: "required",
    validate: (v: Fruit | null) => (v ? null : "Please select a fruit"),
  });

  const logic = new SelectLogic<Fruit>({
    rules: [required()],
    validateOnBlur: true,
    validateOnChange: false,
  });

  const state = useLogic(logic);

  function handleSelect(value: Fruit) {
    logic.setValue(value);
  }
</script>

<h2>Select</h2>

<div class="demo">
  <label class="label">Favorite fruit</label>

  <div class="select-wrapper">
    <button class="select-trigger" onclick={() => logic.toggleMenu()}>
      {#if state.current.value}
        {options.find((o) => o.value === state.current.value)?.label}
      {:else}
        <span class="placeholder">Choose a fruit…</span>
      {/if}
      <span class="chevron">{state.current.open ? "▲" : "▼"}</span>
    </button>

    {#if state.current.open}
      <ul class="dropdown">
        {#each options as opt}
          <li>
            <button
              class="option"
              class:selected={state.current.value === opt.value}
              onclick={() => handleSelect(opt.value)}
            >
              {opt.label}
            </button>
          </li>
        {/each}
      </ul>
    {/if}
  </div>

  {#if !state.current.validation.valid && state.current.touched}
    <ul class="errors">
      {#each state.current.validation.errors as err}
        <li>{err}</li>
      {/each}
    </ul>
  {/if}

  <div class="state-debug">
    <strong>State:</strong>
    <code>
      value={state.current.value ?? "null"} | open={state.current.open} |
      touched={state.current.touched} | dirty={state.current.dirty} |
      valid={state.current.validation.valid}
    </code>
  </div>

  <div class="actions">
    <button onclick={() => logic.reset()}>Reset</button>
    <button onclick={() => logic.validate()}>Validate</button>
  </div>
</div>

<style>
  .demo {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .label {
    font-weight: 600;
    font-size: 0.875rem;
  }
  .select-wrapper {
    position: relative;
    width: 100%;
  }
  .select-trigger {
    width: 100%;
    padding: 0.5rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    background: var(--color-surface);
    font-size: 0.875rem;
    text-align: left;
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .select-trigger:hover {
    border-color: var(--color-text-muted);
  }
  .placeholder {
    color: var(--color-text-muted);
  }
  .chevron {
    font-size: 0.65rem;
    color: var(--color-text-muted);
  }
  .dropdown {
    position: absolute;
    top: calc(100% + 4px);
    left: 0;
    right: 0;
    list-style: none;
    padding: 0.25rem 0;
    margin: 0;
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    box-shadow: var(--shadow);
    z-index: 10;
  }
  .option {
    width: 100%;
    padding: 0.4rem 0.75rem;
    border: none;
    background: none;
    font-size: 0.875rem;
    text-align: left;
    cursor: pointer;
  }
  .option:hover {
    background: var(--color-bg);
  }
  .option.selected {
    color: var(--color-primary);
    font-weight: 600;
  }
  .errors {
    color: var(--color-error);
    font-size: 0.8rem;
    padding-left: 1rem;
  }
  .state-debug {
    font-size: 0.75rem;
    color: var(--color-text-muted);
    background: var(--color-bg);
    padding: 0.5rem;
    border-radius: var(--radius);
  }
  .state-debug code {
    display: block;
    margin-top: 0.25rem;
  }
  .actions {
    display: flex;
    gap: 0.5rem;
  }
  .actions button {
    padding: 0.375rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius);
    background: var(--color-surface);
    cursor: pointer;
    font-size: 0.8rem;
  }
  .actions button:hover {
    background: var(--color-bg);
  }
</style>
